/*
 * Copyright (c) 2026 Swagat Samal
 * Licensed under CC BY-NC-ND 4.0
 * https://creativecommons.org/licenses/by-nc-nd/4.0/
 */
package com.sales;

import java.io.*;
import java.util.*;

public class ChartExporter {

    public static void export(int[] clusters, String[] labels,
                              List<double[]> features, List<String[]> meta) throws Exception {

        int[] counts = new int[4];
        for (int c : clusters) if (c >= 0 && c < 4) counts[c]++;

        StringBuilder[] pts = new StringBuilder[4];
        for (int i=0; i<4; i++) pts[i] = new StringBuilder();
        for (int i = 0; i < features.size(); i++) {
            double[] f = features.get(i);
            String n = meta.get(i)[1].replace("'", "");
            int c = clusters[i];
            if (c >= 0 && c < 4)
                pts[c].append("{x:").append((int)f[0])
                        .append(",y:").append((long)f[2])
                        .append(",name:'").append(n).append("'},");
        }

        new File("output").mkdirs();
        try (PrintWriter pw = new PrintWriter(new FileWriter("output/dashboard.html"))) {
            pw.println("<html><head><title>Sales Dashboard</title>");
            pw.println("<script src='https://cdn.jsdelivr.net/npm/chart.js'></script>");
            pw.println("<style>");
            pw.println("body { font-family: 'Segoe UI', sans-serif; background: #f0f2f5; padding: 20px; }");
            pw.println(".row { display: flex; gap: 20px; margin-bottom: 20px; }");
            pw.println(".card { background: white; padding: 20px; border-radius: 12px; box-shadow: 0 4px 6px rgba(0,0,0,0.05); flex: 1; }");
            pw.println(".stat-val { font-size: 24px; font-weight: bold; color: #1a73e8; }");
            pw.println("canvas { max-height: 400px; }");
            pw.println("</style></head><body>");

            pw.println("<h1>Sales Intelligence Dashboard</h1>");
            pw.println("<p>Generated by SalesIntelligence v1.0 • " + new java.util.Date() + "</p>");

            pw.println("<div class='row'>");
            pw.println("<div class='card'><div>Total Customers</div><div class='stat-val'>" + features.size() + "</div></div>");
            pw.println("<div class='card'><div>Premium Segment</div><div class='stat-val'>" + counts[0] + "</div></div>");
            pw.println("<div class='card'><div>Segments Identified</div><div class='stat-val'>4</div></div>");
            pw.println("</div>");

            pw.println("<div class='row'>");
            pw.println("<div class='card'><h3>Customer Cluster Distribution</h3><canvas id='pieChart'></canvas></div>");
            pw.println("<div class='card'><h3>Recency vs Monetary</h3><canvas id='scatterChart'></canvas></div>");
            pw.println("</div>");

            pw.println("<script>");
            pw.println("const colors = ['#4472C4','#70AD47','#FFC000','#FF4444'];");

            pw.println("new Chart('pieChart', { type: 'pie', data: {");
            pw.println("labels: ['Premium', 'Growth', 'At-Risk', 'Lost'],");
            pw.println("datasets: [{ data: [" + counts[0] + "," + counts[1] + "," + counts[2] + "," + counts[3] + "], backgroundColor: colors }]");
            pw.println("}});");

            pw.println("new Chart('scatterChart', { type: 'scatter', data: { datasets: [");
            for(int i=0; i<4; i++) {
                pw.println("{ label: '" + labels[i] + "', data: [" + pts[i].toString() + "], backgroundColor: colors["+i+"] },");
            }
            pw.println("]}, options: { scales: { x: {title:{display:true, text:'Recency'}}, y: {title:{display:true, text:'Monetary'}} } } });");
            pw.println("</script>");

            pw.println("</body></html>");
        }
        System.out.println("  Dashboard → output/dashboard.html (open in Chrome)");
    }
}